// Package network provides Go bindings for the `Network` domain
// (https://chromedevtools.github.io/devtools-protocol/tot/Network)
// in the Chrome DevTools Protocol (CDP), version 1.3.
//
// Network domain allows tracking network activities of the page. It exposes information about http,
// file, data and other requests and responses, their headers, bodies, timing, etc.
//
// Code generated by https://github.com/daabr/chrome-vision/cmd/cdpgen - DO NOT EDIT.
package network
