// Package performancetimeline provides Go bindings for the `PerformanceTimeline` domain
// (https://chromedevtools.github.io/devtools-protocol/tot/PerformanceTimeline)
// in the Chrome DevTools Protocol (CDP), version 1.3.
//
// Reporting of performance timeline events, as specified in
// https://w3c.github.io/performance-timeline/#dom-performanceobserver.
//
// This domain is experimental!
//
// Code generated by https://github.com/daabr/chrome-vision/cmd/cdpgen - DO NOT EDIT.
package performancetimeline
