// Package database provides Go bindings for the `Database` domain
// (https://chromedevtools.github.io/devtools-protocol/tot/Database)
// in the Chrome DevTools Protocol (CDP), version 1.3.
//
// This domain is experimental!
//
// Code generated by https://github.com/daabr/chrome-vision/cmd/cdpgen - DO NOT EDIT.
package database
