// Package media provides Go bindings for the `Media` domain
// (https://chromedevtools.github.io/devtools-protocol/tot/Media)
// in the Chrome DevTools Protocol (CDP), version 1.3.
//
// This domain allows detailed inspection of media elements
//
// This domain is experimental!
//
// Code generated by https://github.com/daabr/chrome-vision/cmd/cdpgen - DO NOT EDIT.
package media
