// Package backgroundservice provides Go bindings for the `BackgroundService` domain
// (https://chromedevtools.github.io/devtools-protocol/tot/BackgroundService)
// in the Chrome DevTools Protocol (CDP), version 1.3.
//
// Defines events for background web platform features.
//
// This domain is experimental!
//
// Code generated by https://github.com/daabr/chrome-vision/cmd/cdpgen - DO NOT EDIT.
package backgroundservice
