// Package debugger provides Go bindings for the `Debugger` domain
// (https://chromedevtools.github.io/devtools-protocol/tot/Debugger)
// in the Chrome DevTools Protocol (CDP), version 1.3.
//
// Debugger domain exposes JavaScript debugging capabilities. It allows setting and removing
// breakpoints, stepping through execution, exploring stack traces, etc.
//
// Code generated by https://github.com/daabr/chrome-vision/cmd/cdpgen - DO NOT EDIT.
package debugger
