// Package browser provides Go bindings for the `Browser` domain
// (https://chromedevtools.github.io/devtools-protocol/tot/Browser)
// in the Chrome DevTools Protocol (CDP), version 1.3.
//
// The Browser domain defines methods and events for browser managing.
//
// Code generated by https://github.com/daabr/chrome-vision/cmd/cdpgen - DO NOT EDIT.
package browser
