// Package console provides Go bindings for the `Console` domain
// (https://chromedevtools.github.io/devtools-protocol/tot/Console)
// in the Chrome DevTools Protocol (CDP), version 1.3.
//
// This domain is deprecated - use Runtime or Log instead.
//
// Code generated by https://github.com/daabr/chrome-vision/cmd/cdpgen - DO NOT EDIT.
package console
