// Package runtime provides Go bindings for the `Runtime` domain
// (https://chromedevtools.github.io/devtools-protocol/tot/Runtime)
// in the Chrome DevTools Protocol (CDP), version 1.3.
//
// Runtime domain exposes JavaScript runtime by means of remote evaluation and mirror objects.
// Evaluation results are returned as mirror object that expose object type, string representation
// and unique identifier that can be used for further object reference. Original objects are
// maintained in memory unless they are either explicitly released or are released along with the
// other objects in their object group.
//
// Code generated by https://github.com/daabr/chrome-vision/cmd/cdpgen - DO NOT EDIT.
package runtime
