// Package page provides Go bindings for the `Page` domain
// (https://chromedevtools.github.io/devtools-protocol/tot/Page)
// in the Chrome DevTools Protocol (CDP), version 1.3.
//
// Actions and events related to the inspected page belong to the page domain.
//
// Code generated by https://github.com/daabr/chrome-vision/cmd/cdpgen - DO NOT EDIT.
package page
