// Package eventbreakpoints provides Go bindings for the `EventBreakpoints` domain
// (https://chromedevtools.github.io/devtools-protocol/tot/EventBreakpoints)
// in the Chrome DevTools Protocol (CDP), version 1.3.
//
// EventBreakpoints permits setting breakpoints on particular operations and
// events in targets that run JavaScript but do not have a DOM.
// JavaScript execution will stop on these operations as if there was a regular
// breakpoint set.
//
// This domain is experimental!
//
// Code generated by https://github.com/daabr/chrome-vision/cmd/cdpgen - DO NOT EDIT.
package eventbreakpoints
