// Package domsnapshot provides Go bindings for the `DOMSnapshot` domain
// (https://chromedevtools.github.io/devtools-protocol/tot/DOMSnapshot)
// in the Chrome DevTools Protocol (CDP), version 1.3.
//
// This domain facilitates obtaining document snapshots with DOM, layout, and style information.
//
// This domain is experimental!
//
// Code generated by https://github.com/daabr/chrome-vision/cmd/cdpgen - DO NOT EDIT.
package domsnapshot
