// Package dom provides Go bindings for the `DOM` domain
// (https://chromedevtools.github.io/devtools-protocol/tot/DOM)
// in the Chrome DevTools Protocol (CDP), version 1.3.
//
// This domain exposes DOM read/write operations. Each DOM Node is represented with its mirror object
// that has an `id`. This `id` can be used to get additional information on the Node, resolve it into
// the JavaScript object wrapper, etc. It is important that client receives DOM events only for the
// nodes that are known to the client. Backend keeps track of the nodes that were sent to the client
// and never sends the same node twice. It is client's responsibility to collect information about
// the nodes that were sent to the client.
//
// Note that `iframe` owner elements will return
// corresponding document elements as their child nodes.
//
// Code generated by https://github.com/daabr/chrome-vision/cmd/cdpgen - DO NOT EDIT.
package dom
