// Package overlay provides Go bindings for the `Overlay` domain
// (https://chromedevtools.github.io/devtools-protocol/tot/Overlay)
// in the Chrome DevTools Protocol (CDP), version 1.3.
//
// This domain provides various functionality related to drawing atop the inspected page.
//
// This domain is experimental!
//
// Code generated by https://github.com/daabr/chrome-vision/cmd/cdpgen - DO NOT EDIT.
package overlay
