// Package input provides Go bindings for the `Input` domain
// (https://chromedevtools.github.io/devtools-protocol/tot/Input)
// in the Chrome DevTools Protocol (CDP), version 1.3.
//
// Code generated by https://github.com/daabr/chrome-vision/cmd/cdpgen - DO NOT EDIT.
package input
