// Package cast provides Go bindings for the `Cast` domain
// (https://chromedevtools.github.io/devtools-protocol/tot/Cast)
// in the Chrome DevTools Protocol (CDP), version 1.3.
//
// A domain for interacting with Cast, Presentation API, and Remote Playback API
// functionalities.
//
// This domain is experimental!
//
// Code generated by https://github.com/daabr/chrome-vision/cmd/cdpgen - DO NOT EDIT.
package cast
