// Package schema provides Go bindings for the `Schema` domain
// (https://chromedevtools.github.io/devtools-protocol/tot/Schema)
// in the Chrome DevTools Protocol (CDP), version 1.3.
//
// This domain is deprecated.
//
// Code generated by https://github.com/daabr/chrome-vision/cmd/cdpgen - DO NOT EDIT.
package schema
