// Package domdebugger provides Go bindings for the `DOMDebugger` domain
// (https://chromedevtools.github.io/devtools-protocol/tot/DOMDebugger)
// in the Chrome DevTools Protocol (CDP), version 1.3.
//
// DOM debugging allows setting breakpoints on particular DOM operations and events. JavaScript
// execution will stop on these operations as if there was a regular breakpoint set.
//
// Code generated by https://github.com/daabr/chrome-vision/cmd/cdpgen - DO NOT EDIT.
package domdebugger
