// Package io provides Go bindings for the `IO` domain
// (https://chromedevtools.github.io/devtools-protocol/tot/IO)
// in the Chrome DevTools Protocol (CDP), version 1.3.
//
// Input/Output operations for streams produced by DevTools.
//
// Code generated by https://github.com/daabr/chrome-vision/cmd/cdpgen - DO NOT EDIT.
package io
