// Package fetch provides Go bindings for the `Fetch` domain
// (https://chromedevtools.github.io/devtools-protocol/tot/Fetch)
// in the Chrome DevTools Protocol (CDP), version 1.3.
//
// A domain for letting clients substitute browser's network layer with client code.
//
// Code generated by https://github.com/daabr/chrome-vision/cmd/cdpgen - DO NOT EDIT.
package fetch
