// Package headlessexperimental provides Go bindings for the `HeadlessExperimental` domain
// (https://chromedevtools.github.io/devtools-protocol/tot/HeadlessExperimental)
// in the Chrome DevTools Protocol (CDP), version 1.3.
//
// This domain provides experimental commands only supported in headless mode.
//
// This domain is experimental!
//
// Code generated by https://github.com/daabr/chrome-vision/cmd/cdpgen - DO NOT EDIT.
package headlessexperimental
