// Package accessibility provides Go bindings for the `Accessibility` domain
// (https://chromedevtools.github.io/devtools-protocol/tot/Accessibility)
// in the Chrome DevTools Protocol (CDP), version 1.3.
//
// This domain is experimental!
//
// Code generated by https://github.com/daabr/chrome-vision/cmd/cdpgen - DO NOT EDIT.
package accessibility
