// Package domstorage provides Go bindings for the `DOMStorage` domain
// (https://chromedevtools.github.io/devtools-protocol/tot/DOMStorage)
// in the Chrome DevTools Protocol (CDP), version 1.3.
//
// Query and modify DOM storage.
//
// This domain is experimental!
//
// Code generated by https://github.com/daabr/chrome-vision/cmd/cdpgen - DO NOT EDIT.
package domstorage
