// Package webaudio provides Go bindings for the `WebAudio` domain
// (https://chromedevtools.github.io/devtools-protocol/tot/WebAudio)
// in the Chrome DevTools Protocol (CDP), version 1.3.
//
// This domain allows inspection of Web Audio API.
// https://webaudio.github.io/web-audio-api/
//
// This domain is experimental!
//
// Code generated by https://github.com/daabr/chrome-vision/cmd/cdpgen - DO NOT EDIT.
package webaudio
