// Package security provides Go bindings for the `Security` domain
// (https://chromedevtools.github.io/devtools-protocol/tot/Security)
// in the Chrome DevTools Protocol (CDP), version 1.3.
//
// Security
//
// Code generated by https://github.com/daabr/chrome-vision/cmd/cdpgen - DO NOT EDIT.
package security
