// Package emulation provides Go bindings for the `Emulation` domain
// (https://chromedevtools.github.io/devtools-protocol/tot/Emulation)
// in the Chrome DevTools Protocol (CDP), version 1.3.
//
// This domain emulates different environments for the page.
//
// Code generated by https://github.com/daabr/chrome-vision/cmd/cdpgen - DO NOT EDIT.
package emulation
