// Package webauthn provides Go bindings for the `WebAuthn` domain
// (https://chromedevtools.github.io/devtools-protocol/tot/WebAuthn)
// in the Chrome DevTools Protocol (CDP), version 1.3.
//
// This domain allows configuring virtual authenticators to test the WebAuthn
// API.
//
// This domain is experimental!
//
// Code generated by https://github.com/daabr/chrome-vision/cmd/cdpgen - DO NOT EDIT.
package webauthn
