// Package audits provides Go bindings for the `Audits` domain
// (https://chromedevtools.github.io/devtools-protocol/tot/Audits)
// in the Chrome DevTools Protocol (CDP), version 1.3.
//
// Audits domain allows investigation of page violations and possible improvements.
//
// This domain is experimental!
//
// Code generated by https://github.com/daabr/chrome-vision/cmd/cdpgen - DO NOT EDIT.
package audits
