// Package log provides Go bindings for the `Log` domain
// (https://chromedevtools.github.io/devtools-protocol/tot/Log)
// in the Chrome DevTools Protocol (CDP), version 1.3.
//
// Provides access to log entries.
//
// Code generated by https://github.com/daabr/chrome-vision/cmd/cdpgen - DO NOT EDIT.
package log
