// Package systeminfo provides Go bindings for the `SystemInfo` domain
// (https://chromedevtools.github.io/devtools-protocol/tot/SystemInfo)
// in the Chrome DevTools Protocol (CDP), version 1.3.
//
// The SystemInfo domain defines methods and events for querying low-level system information.
//
// This domain is experimental!
//
// Code generated by https://github.com/daabr/chrome-vision/cmd/cdpgen - DO NOT EDIT.
package systeminfo
