// Package tethering provides Go bindings for the `Tethering` domain
// (https://chromedevtools.github.io/devtools-protocol/tot/Tethering)
// in the Chrome DevTools Protocol (CDP), version 1.3.
//
// The Tethering domain defines methods and events for browser port binding.
//
// This domain is experimental!
//
// Code generated by https://github.com/daabr/chrome-vision/cmd/cdpgen - DO NOT EDIT.
package tethering
