// Package profiler provides Go bindings for the `Profiler` domain
// (https://chromedevtools.github.io/devtools-protocol/tot/Profiler)
// in the Chrome DevTools Protocol (CDP), version 1.3.
//
// Code generated by https://github.com/daabr/chrome-vision/cmd/cdpgen - DO NOT EDIT.
package profiler
