name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Install dependencies
      run: |
        go get -u golang.org/x/lint/golint
        echo $PATH
        echo $GOBIN
        ls /usr/local/go/bin
        pwd
        ls ~/go/bin

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest] # TODO: , windows-latest]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v $(go list ./... | grep -v /pkg/cdp/)

    - name: Race detection
      run: go test -race -v $(go list ./... | grep -v /pkg/cdp/)

    - name: Coverage analysis
      run: |
        go test -covermode=atomic -coverprofile=coverage.out -race -v $(go list ./... | grep -v /pkg/cdp/)
        cat coverage.out
        go tool cover -func=coverage.out
        # go tool cover -html=coverage.out
