name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Install dependencies
      run: go get -u golang.org/x/lint/golint

    - name: Lint
      run: ~/go/bin/golint ./... -set_exit_status

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v $(go list ./... | grep -v /pkg/devtools/)

    - name: Race detection
      run: go test -race -v $(go list ./... | grep -v /pkg/devtools/)

  coverage:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Coverage analysis
      run: |
        go test -covermode=atomic -coverprofile=coverage.out -race $(go list ./... | grep -v /pkg/devtools/)
        echo
        cat coverage.out
        echo
        go tool cover -func=coverage.out
        # Run manually with coverage.out: go tool cover -html=coverage.out
